# coding: utf-8

"""
    OpenDota API

    # Introduction This API provides Dota 2 related data. Please keep request rate to approximately 3/s. 

    OpenAPI spec version: 15.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.records_api import RecordsApi


class TestRecordsApi(unittest.TestCase):
    """ RecordsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.records_api.RecordsApi()

    def tearDown(self):
        pass

    def test_records_field_get(self):
        """
        Test case for records_field_get

        GET /records/{field}
        """
        pass


if __name__ == '__main__':
    unittest.main()
