# coding: utf-8

"""
    OpenDota API

    # Introduction This API provides Dota 2 related data. Please keep request rate to approximately 3/s. 

    OpenAPI spec version: 15.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import od_python
from od_python.rest import ApiException
from od_python.models.inline_response_200_13 import InlineResponse20013


class TestInlineResponse20013(unittest.TestCase):
    """ InlineResponse20013 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20013(self):
        """
        Test InlineResponse20013
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = od_python.models.inline_response_200_13.InlineResponse20013()
        pass


if __name__ == '__main__':
    unittest.main()
