# coding: utf-8

"""
    OpenDota API

    # Introduction This API provides Dota 2 related data. Please keep request rate to approximately 3/s. 

    OpenAPI spec version: 15.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.inline_response_200_1_profile import InlineResponse2001Profile


class TestInlineResponse2001Profile(unittest.TestCase):
    """ InlineResponse2001Profile unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2001Profile(self):
        """
        Test InlineResponse2001Profile
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.inline_response_200_1_profile.InlineResponse2001Profile()
        pass


if __name__ == '__main__':
    unittest.main()
