# coding: utf-8

"""
    OpenDota API

    # Introduction This API provides Dota 2 related data. Please keep request rate to approximately 3/s. 

    OpenAPI spec version: 16.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import od_python
from od_python.rest import ApiException
from od_python.models.inline_response_200_buyback_log import InlineResponse200BuybackLog


class TestInlineResponse200BuybackLog(unittest.TestCase):
    """ InlineResponse200BuybackLog unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200BuybackLog(self):
        """
        Test InlineResponse200BuybackLog
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = od_python.models.inline_response_200_buyback_log.InlineResponse200BuybackLog()
        pass


if __name__ == '__main__':
    unittest.main()
