# coding: utf-8

"""
    OpenDota API

    # Introduction This API provides Dota 2 related data. Please keep request rate to approximately 3/s. 

    OpenAPI spec version: 17.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import od_python
from od_python.rest import ApiException
from od_python.models.inline_response_200_18 import InlineResponse20018


class TestInlineResponse20018(unittest.TestCase):
    """ InlineResponse20018 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20018(self):
        """
        Test InlineResponse20018
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = od_python.models.inline_response_200_18.InlineResponse20018()
        pass


if __name__ == '__main__':
    unittest.main()
