# coding: utf-8

"""
    OpenDota API

    # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays. Please keep request rate to approximately 1/s.  **Begining 4/22/2018, the OpenDota API will be limited to 50,000 free calls per month.** We'll be offering a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more. 

    OpenAPI spec version: 17.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import od_python
from od_python.rest import ApiException
from od_python.apis.health_api import HealthApi


class TestHealthApi(unittest.TestCase):
    """ HealthApi unit test stubs """

    def setUp(self):
        self.api = od_python.apis.health_api.HealthApi()

    def tearDown(self):
        pass

    def test_health_get(self):
        """
        Test case for health_get

        GET /health
        """
        pass


if __name__ == '__main__':
    unittest.main()
