# coding: utf-8

"""
    OpenDota API

    # Introduction This API provides Dota 2 related data. Please keep request rate to approximately 3/s. 

    OpenAPI spec version: 15.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.inline_response_200_17_cheese import InlineResponse20017Cheese


class TestInlineResponse20017Cheese(unittest.TestCase):
    """ InlineResponse20017Cheese unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20017Cheese(self):
        """
        Test InlineResponse20017Cheese
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.inline_response_200_17_cheese.InlineResponse20017Cheese()
        pass


if __name__ == '__main__':
    unittest.main()
