# coding: utf-8

"""
    OpenDota API

    # Introduction This API provides Dota 2 related data. Please keep request rate to approximately 3/s. 

    OpenAPI spec version: 15.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.inline_response_200_20_rankings import InlineResponse20020Rankings


class TestInlineResponse20020Rankings(unittest.TestCase):
    """ InlineResponse20020Rankings unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20020Rankings(self):
        """
        Test InlineResponse20020Rankings
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.inline_response_200_20_rankings.InlineResponse20020Rankings()
        pass


if __name__ == '__main__':
    unittest.main()
