# coding: utf-8

"""
    OpenDota API

    # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays. Please keep request rate to approximately 1/s.  **Begining 4/22/2018, the OpenDota API will be limited to 50,000 free calls per month.** We'll be offering a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more. 

    OpenAPI spec version: 17.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class InlineResponse20017CountryMmrRows(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'loccountrycode': 'str',
        'count': 'int',
        'avg': 'str',
        'common': 'str'
    }

    attribute_map = {
        'loccountrycode': 'loccountrycode',
        'count': 'count',
        'avg': 'avg',
        'common': 'common'
    }

    def __init__(self, loccountrycode=None, count=None, avg=None, common=None):
        """
        InlineResponse20017CountryMmrRows - a model defined in Swagger
        """

        self._loccountrycode = None
        self._count = None
        self._avg = None
        self._common = None

        if loccountrycode is not None:
          self.loccountrycode = loccountrycode
        if count is not None:
          self.count = count
        if avg is not None:
          self.avg = avg
        if common is not None:
          self.common = common

    @property
    def loccountrycode(self):
        """
        Gets the loccountrycode of this InlineResponse20017CountryMmrRows.
        loccountrycode

        :return: The loccountrycode of this InlineResponse20017CountryMmrRows.
        :rtype: str
        """
        return self._loccountrycode

    @loccountrycode.setter
    def loccountrycode(self, loccountrycode):
        """
        Sets the loccountrycode of this InlineResponse20017CountryMmrRows.
        loccountrycode

        :param loccountrycode: The loccountrycode of this InlineResponse20017CountryMmrRows.
        :type: str
        """

        self._loccountrycode = loccountrycode

    @property
    def count(self):
        """
        Gets the count of this InlineResponse20017CountryMmrRows.
        count

        :return: The count of this InlineResponse20017CountryMmrRows.
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """
        Sets the count of this InlineResponse20017CountryMmrRows.
        count

        :param count: The count of this InlineResponse20017CountryMmrRows.
        :type: int
        """

        self._count = count

    @property
    def avg(self):
        """
        Gets the avg of this InlineResponse20017CountryMmrRows.
        avg

        :return: The avg of this InlineResponse20017CountryMmrRows.
        :rtype: str
        """
        return self._avg

    @avg.setter
    def avg(self, avg):
        """
        Sets the avg of this InlineResponse20017CountryMmrRows.
        avg

        :param avg: The avg of this InlineResponse20017CountryMmrRows.
        :type: str
        """

        self._avg = avg

    @property
    def common(self):
        """
        Gets the common of this InlineResponse20017CountryMmrRows.
        common

        :return: The common of this InlineResponse20017CountryMmrRows.
        :rtype: str
        """
        return self._common

    @common.setter
    def common(self, common):
        """
        Sets the common of this InlineResponse20017CountryMmrRows.
        common

        :param common: The common of this InlineResponse20017CountryMmrRows.
        :type: str
        """

        self._common = common

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, InlineResponse20017CountryMmrRows):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
