# coding: utf-8

"""
    OpenDota API

    # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays. Please keep request rate to approximately 1/s.  **Begining 4/22/2018, the OpenDota API will be limited to 50,000 free calls per month.** We'll be offering a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more. 

    OpenAPI spec version: 17.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class InlineResponse20026(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'account_id': 'str',
        'name': 'str',
        'games_played': 'int',
        'wins': 'int',
        'is_current_team_member': 'bool'
    }

    attribute_map = {
        'account_id': 'account_id',
        'name': 'name',
        'games_played': 'games_played',
        'wins': 'wins',
        'is_current_team_member': 'is_current_team_member'
    }

    def __init__(self, account_id=None, name=None, games_played=None, wins=None, is_current_team_member=None):
        """
        InlineResponse20026 - a model defined in Swagger
        """

        self._account_id = None
        self._name = None
        self._games_played = None
        self._wins = None
        self._is_current_team_member = None

        if account_id is not None:
          self.account_id = account_id
        if name is not None:
          self.name = name
        if games_played is not None:
          self.games_played = games_played
        if wins is not None:
          self.wins = wins
        if is_current_team_member is not None:
          self.is_current_team_member = is_current_team_member

    @property
    def account_id(self):
        """
        Gets the account_id of this InlineResponse20026.
        The player account ID

        :return: The account_id of this InlineResponse20026.
        :rtype: str
        """
        return self._account_id

    @account_id.setter
    def account_id(self, account_id):
        """
        Sets the account_id of this InlineResponse20026.
        The player account ID

        :param account_id: The account_id of this InlineResponse20026.
        :type: str
        """

        self._account_id = account_id

    @property
    def name(self):
        """
        Gets the name of this InlineResponse20026.
        The player name

        :return: The name of this InlineResponse20026.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this InlineResponse20026.
        The player name

        :param name: The name of this InlineResponse20026.
        :type: str
        """

        self._name = name

    @property
    def games_played(self):
        """
        Gets the games_played of this InlineResponse20026.
        Number of games played

        :return: The games_played of this InlineResponse20026.
        :rtype: int
        """
        return self._games_played

    @games_played.setter
    def games_played(self, games_played):
        """
        Sets the games_played of this InlineResponse20026.
        Number of games played

        :param games_played: The games_played of this InlineResponse20026.
        :type: int
        """

        self._games_played = games_played

    @property
    def wins(self):
        """
        Gets the wins of this InlineResponse20026.
        Number of wins

        :return: The wins of this InlineResponse20026.
        :rtype: int
        """
        return self._wins

    @wins.setter
    def wins(self, wins):
        """
        Sets the wins of this InlineResponse20026.
        Number of wins

        :param wins: The wins of this InlineResponse20026.
        :type: int
        """

        self._wins = wins

    @property
    def is_current_team_member(self):
        """
        Gets the is_current_team_member of this InlineResponse20026.
        If this player is on the current roster

        :return: The is_current_team_member of this InlineResponse20026.
        :rtype: bool
        """
        return self._is_current_team_member

    @is_current_team_member.setter
    def is_current_team_member(self, is_current_team_member):
        """
        Sets the is_current_team_member of this InlineResponse20026.
        If this player is on the current roster

        :param is_current_team_member: The is_current_team_member of this InlineResponse20026.
        :type: bool
        """

        self._is_current_team_member = is_current_team_member

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, InlineResponse20026):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
