# coding: utf-8

"""
    OpenDota API

    # Introduction This API provides Dota 2 related data. Please keep request rate to approximately 3/s. 

    OpenAPI spec version: 17.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class InlineResponse20020(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'hero_id': 'int',
        'rankings': 'InlineResponse20020Rankings'
    }

    attribute_map = {
        'hero_id': 'hero_id',
        'rankings': 'rankings'
    }

    def __init__(self, hero_id=None, rankings=None):
        """
        InlineResponse20020 - a model defined in Swagger
        """

        self._hero_id = None
        self._rankings = None

        if hero_id is not None:
          self.hero_id = hero_id
        if rankings is not None:
          self.rankings = rankings

    @property
    def hero_id(self):
        """
        Gets the hero_id of this InlineResponse20020.
        hero_id

        :return: The hero_id of this InlineResponse20020.
        :rtype: int
        """
        return self._hero_id

    @hero_id.setter
    def hero_id(self, hero_id):
        """
        Sets the hero_id of this InlineResponse20020.
        hero_id

        :param hero_id: The hero_id of this InlineResponse20020.
        :type: int
        """

        self._hero_id = hero_id

    @property
    def rankings(self):
        """
        Gets the rankings of this InlineResponse20020.

        :return: The rankings of this InlineResponse20020.
        :rtype: InlineResponse20020Rankings
        """
        return self._rankings

    @rankings.setter
    def rankings(self, rankings):
        """
        Sets the rankings of this InlineResponse20020.

        :param rankings: The rankings of this InlineResponse20020.
        :type: InlineResponse20020Rankings
        """

        self._rankings = rankings

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, InlineResponse20020):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
