# coding: utf-8

"""
    OpenDota API

    # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays. Please keep request rate to approximately 1/s.  **Begining 4/22/2018, the OpenDota API will be limited to 50,000 free calls per month.** We'll be offering a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more. 

    OpenAPI spec version: 17.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class InlineResponse20023(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'duration_bin': 'str',
        'games_played': 'int',
        'wins': 'int'
    }

    attribute_map = {
        'duration_bin': 'duration_bin',
        'games_played': 'games_played',
        'wins': 'wins'
    }

    def __init__(self, duration_bin=None, games_played=None, wins=None):
        """
        InlineResponse20023 - a model defined in Swagger
        """

        self._duration_bin = None
        self._games_played = None
        self._wins = None

        if duration_bin is not None:
          self.duration_bin = duration_bin
        if games_played is not None:
          self.games_played = games_played
        if wins is not None:
          self.wins = wins

    @property
    def duration_bin(self):
        """
        Gets the duration_bin of this InlineResponse20023.
        Lower bound of number of seconds the match lasted

        :return: The duration_bin of this InlineResponse20023.
        :rtype: str
        """
        return self._duration_bin

    @duration_bin.setter
    def duration_bin(self, duration_bin):
        """
        Sets the duration_bin of this InlineResponse20023.
        Lower bound of number of seconds the match lasted

        :param duration_bin: The duration_bin of this InlineResponse20023.
        :type: str
        """

        self._duration_bin = duration_bin

    @property
    def games_played(self):
        """
        Gets the games_played of this InlineResponse20023.
        Number of games played

        :return: The games_played of this InlineResponse20023.
        :rtype: int
        """
        return self._games_played

    @games_played.setter
    def games_played(self, games_played):
        """
        Sets the games_played of this InlineResponse20023.
        Number of games played

        :param games_played: The games_played of this InlineResponse20023.
        :type: int
        """

        self._games_played = games_played

    @property
    def wins(self):
        """
        Gets the wins of this InlineResponse20023.
        Number of wins

        :return: The wins of this InlineResponse20023.
        :rtype: int
        """
        return self._wins

    @wins.setter
    def wins(self, wins):
        """
        Sets the wins of this InlineResponse20023.
        Number of wins

        :param wins: The wins of this InlineResponse20023.
        :type: int
        """

        self._wins = wins

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, InlineResponse20023):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
