# coding: utf-8

"""
    OpenDota API

    # Introduction This API provides Dota 2 related data. Please keep request rate to approximately 3/s. 

    OpenAPI spec version: 17.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class InlineResponse2008(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'field': 'str',
        'n': 'int',
        'sum': 'int'
    }

    attribute_map = {
        'field': 'field',
        'n': 'n',
        'sum': 'sum'
    }

    def __init__(self, field=None, n=None, sum=None):
        """
        InlineResponse2008 - a model defined in Swagger
        """

        self._field = None
        self._n = None
        self._sum = None

        if field is not None:
          self.field = field
        if n is not None:
          self.n = n
        if sum is not None:
          self.sum = sum

    @property
    def field(self):
        """
        Gets the field of this InlineResponse2008.
        field

        :return: The field of this InlineResponse2008.
        :rtype: str
        """
        return self._field

    @field.setter
    def field(self, field):
        """
        Sets the field of this InlineResponse2008.
        field

        :param field: The field of this InlineResponse2008.
        :type: str
        """

        self._field = field

    @property
    def n(self):
        """
        Gets the n of this InlineResponse2008.
        number

        :return: The n of this InlineResponse2008.
        :rtype: int
        """
        return self._n

    @n.setter
    def n(self, n):
        """
        Sets the n of this InlineResponse2008.
        number

        :param n: The n of this InlineResponse2008.
        :type: int
        """

        self._n = n

    @property
    def sum(self):
        """
        Gets the sum of this InlineResponse2008.
        sum

        :return: The sum of this InlineResponse2008.
        :rtype: int
        """
        return self._sum

    @sum.setter
    def sum(self, sum):
        """
        Sets the sum of this InlineResponse2008.
        sum

        :param sum: The sum of this InlineResponse2008.
        :type: int
        """

        self._sum = sum

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, InlineResponse2008):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
