# coding: utf-8

"""
    OpenDota API

    # Introduction This API provides Dota 2 related data. Please keep request rate to approximately 3/s. 

    OpenAPI spec version: 15.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class InlineResponse20010(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'obs': 'object',
        'sen': 'object'
    }

    attribute_map = {
        'obs': 'obs',
        'sen': 'sen'
    }

    def __init__(self, obs=None, sen=None):
        """
        InlineResponse20010 - a model defined in Swagger
        """

        self._obs = None
        self._sen = None

        if obs is not None:
          self.obs = obs
        if sen is not None:
          self.sen = sen

    @property
    def obs(self):
        """
        Gets the obs of this InlineResponse20010.
        obs

        :return: The obs of this InlineResponse20010.
        :rtype: object
        """
        return self._obs

    @obs.setter
    def obs(self, obs):
        """
        Sets the obs of this InlineResponse20010.
        obs

        :param obs: The obs of this InlineResponse20010.
        :type: object
        """

        self._obs = obs

    @property
    def sen(self):
        """
        Gets the sen of this InlineResponse20010.
        sen

        :return: The sen of this InlineResponse20010.
        :rtype: object
        """
        return self._sen

    @sen.setter
    def sen(self, sen):
        """
        Sets the sen of this InlineResponse20010.
        sen

        :param sen: The sen of this InlineResponse20010.
        :type: object
        """

        self._sen = sen

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, InlineResponse20010):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
